name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync files to EC2
      run: |
        rsync -avz --delete \
          --exclude='.git*' \
          --exclude='node_modules' \
          ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/myportfolio
      # rsync ensures only changes are transferred :contentReference[oaicite:2]{index=2}

    - name: Run deployment commands on EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /var/www/myportfolio
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          sudo systemctl restart php8.2-fpm
          sudo systemctl reload nginx
        EOF
